### PR TITLE
Audiobookshelf service

### PR DESCRIPTION
**Pull request by sivertism**
Hi,

I tried adding [Audiobookshelf](https://www.audiobookshelf.org/) as a new service to SHB.

Not sure whether you want this service in SHB at all, but thought I'd create a PR just in case.

The service runs, but seemingly fails to add an entry to the nginx config, so it is not reachable. I created the service by basically just copying deluge and then adapting. Any idea why the nginx subdomain isn't being created?

The config I used to add this to my SHB server is:

```nix
shb.audiobookshelf = {
  enable = true;
  domain = "sliper.xyz";
  subdomain = "abs";
  dataDir = "audiobookshelf"; #turns out this is actually the working dir of the service (/var/lib/<dataDir>)
  authEndpoint = "https://auth.sliper.xyz";
};
 // ... in shb.authelia.oidcClients
redirect_uris = [ "https://deluge.sliper.xyz" "https://abs.sliper.xyz" ];
```

ps. I also need to fix tabs->spaces. Forgot to set up nvim.

### CODE REVIEW

**Comment by ibizaman** [comment]
Hi! Thank you for opening this PR. Nothing strikes me as wrong from what I could see but I’ll run it this evening.

Did you see any error in journalctl for nginx or another service?

**Comment by sivertism** [comment]
🤦 The issue was that I'd forgotten to add my user to the `audiobookshelf_user` ldap group! Well I guess now I've tested that the group works!

Looks like Audiobookshelf supports OIDC, so I suppose that's next 👍

**Comment by ibizaman** [comment]
I see. That’s so easy to miss. It happened to me a few times before. There’s at least 2 issues that must be solved for this to be more convenient:
- Creating a group declaratively #16 
- Have an actual error page if trying to access a sub domain that does not exist instead of showing the Authelia auth page.

**Comment by sivertism** [comment]
Creating groups declaratively would definitely be nice. I was thinking about declaring both users and groups declaratively, actually. For the home use case, I can't foresee having to add that many users since it's just a home server, so it would be handy to just do it in the nix config. Then I suppose I wouldn't even need the LLDAP web UI.

**Comment by sivertism** [comment]
Tried setting up OIDC according to [this guide](https://www.audiobookshelf.org/guides/oidc_authentication) and copying stuff from the jellyfin service. 

The redirect to authelia seems to work fine, but it doesn't send me back after authentication. Feels a bit like when I'd forgotten to add my user to the `audiobookshelf_user` group!

**Comment by sivertism** [comment]
There seems to be no way to set the group from the audiobookshelf OIDC setup :thinking: 

There are some URLs that are autodiscovered. Maybe one of them should be modified to select the group? 

image

**Comment by ibizaman** [comment]
Indeed I don't see a mention of group in https://www.audiobookshelf.org/guides/oidc_authentication/

There are a few issues related to OIDC https://github.com/search?q=repo%3Aadvplyr%2Faudiobookshelf+oidc&type=issues A quick survey didn't bring any relevant "group" option.

**Comment by ibizaman** [comment]
You can if you want stop here as far as implementation goes. Or maybe resort back instead to forward auth? Or something cool would be to allow both. Not sure what's the best option here.

**Comment by sivertism** [comment]
Yeah, you're probably right -- OIDC seems to still be under active development in audiobookshelf, so it might be better to wait for it to stabilize regardless.

I asked about this issue on their matrix just now, so I might be able to resolve the issue with some help from them.

Any opinion on how (un) safe it would be to leave audiobookshelf unprotected by authelia? The reason I ask is that their mobile app breaks if I use forward auth.

**Comment by ibizaman** [comment]
Good point about the mobile app. If the mobile app accesses a specific endpoint, say /api/, e we could just protect that endpoint. It would look like the [config for Vaultwarden](https://github.com/ibizaman/selfhostblocks/blob/adc09acc497253835f3d4f2147e8109a820df176/modules/services/vaultwarden.nix#L177) by replacing admin with api and two_factor with bypass IIRC.

**Comment by ibizaman** [comment]
@sivertism anything I can help with to get this merged?
Btw I’d love to add documentation in the manual, tests and a demo with this at some point but it’s not a requisite to getting this merged.

**Comment by sivertism** [comment]
I've been a bit busy with other stuff, but ABS is working as is, albeit with manual SSO config. It's a really great app, been using it a lot thus far!

I've started updating my server to the latest SHB version, and after that I was thinking I'll update ABS, with docs etc. if I find time. So maybe let's wait for that and then merge?

**Comment by ibizaman** [comment]
@sivertism docs would be wonderful! Happy to wait but don’t hesitate to pass the hot potato.

Did you manage to get OIDC working for SSO?

**Comment by sivertism** [comment]
@ibizaman : had a couple of silly issues here on my end after updating, but it is working now.

Setting up SSO is manual, but very straightforward:
1. Log into the root account
2. Go to Settings -> Authentication and enable "OpenID Connect Authentication"
3. Fill in your issuer URL, e.g. https://auth.example.com
4. Click Auto-populate
5. Fill in the client id, `audiobookshelf`
6. Fill in the secret (copied from e.g. `audiobookshelf/sso_secret` in the secrets.yaml file)
7. Enable Auto Register to automatically create users on first login. 
8. Add your user to the `audiobookshelf_user` group on LDAP
9. Log in with through Authelia

[Optional to disable password access]
11. Log in to the root account again, go to Settings->Users and make your authelia/LDAP user admin.
12. Go to Settings->Authentication and disable password access.

**Comment by sivertism** [comment]
Cleaned up the commits. I think it should be ready for merge now (albeit without tests/docs as I ran out of time.)

**Comment by ibizaman** [comment]
I very recently added some tests to Jellyfin, so I ported them over to audiobookshelf. As you can see in my commit, I just needed to enable the nginx service. I missed that too in the Jellyfin service :sweat_smile:

**Comment by ibizaman** [comment]
I spoke too fast, there was one more fix I needed to apply. I had to do that too for Jellyfin but forgot about it.

**Pull request merged**
